### ISSUE TITLE
wrong version of coq-ext-lib installed

### ISSUE THREAD

**Issue by vzaliva** [coq/opam-coq-archive#126]
When I try install `coq-ext-lib` with coq-8.6 it attempts to install 0.9.3 instead of 0.9.5: 
More info:

I have a fresh opam switch with following packages installed:

```
max1 ~/coq/math-classes$ opam list
# Installed packages for 4.04.0.coq.8.6:
base-bigarray   base  Bigarray library distributed with the OCaml compiler
base-threads    base  Threads library distributed with the OCaml compiler
base-unix       base  Unix library distributed with the OCaml compiler
camlp5          6.17  Preprocessor-pretty-printer of OCaml
conf-m4            1  Virtual package relying on m4
coq              8.6  Formal proof management system.
coq-dpdgraph   0.6.1  Compute dependencies between Coq objects (definitions, theorems)
ocamlfind      1.7.1  A library manager for OCaml
ocamlgraph     1.8.7  A generic graph library for OCaml

```

I did `opam update` at it have all versions of the package:

```
max1 ~/coq/math-classes$ opam info coq-ext-lib
             package: coq-ext-lib
             version: 1.0.0~beta2
          repository: coq-released
        upstream-url: https://github.com/coq-ext-lib/coq-ext-lib/archive/v1.0.0-beta2.tar.gz
       upstream-kind: http
   upstream-checksum: a5ba82316433760606fa17535591382a
            homepage: https://github.com/coq-ext-lib/coq-ext-lib
         bug-reports: https://github.com/coq-ext-lib/coq-ext-lib/issues
            dev-repo: https://github.com/coq-ext-lib/coq-ext-lib.git#8.5
              author: Gregory Malecha
             license: BSD
             depends: coq (>= 8.5~beta2 & < 8.5~beta3)
   installed-version: 
  available-versions: 0.9.0~beta3, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 1.0.0~beta2
         description: A library of Coq definitions, theorems, and tactics.

```

I have nothing pinned. However when I try to install it picks up older version:

```
max1 ~/coq/math-classes$ opam instal coq-ext-lib
The following actions will be performed:
  ∗  install coq-ext-lib 0.9.3

```

Which is incompatible with coq-8.6 and the installation fails.
